[program:php-fpm]
command=php-fpm -F
user=root
autostart=true
autorestart=true
stdout_logfile=/var/www/storage/logs/php-fpm.log
stderr_logfile=/var/www/storage/logs/php-fpm.log

[program:reverb]
command=php /var/www/artisan reverb:start --port=8080 --host=0.0.0.0
user=www-data
autostart=true
autorestart=true
stdout_logfile=/var/www/storage/logs/reverb.log
stderr_logfile=/var/www/storage/logs/reverb.log
